FROM ubuntu:16.04
MAINTAINER dayne@alaska.edu
RUN echo "root:Docker!" | chpasswd
RUN  apt-get -q update && \
  apt-get -qy dist-upgrade 
RUN apt-get install -qy git \
  apt-utils \
  vim \
  curl \
  wget \
  zip \
  git \
  bashdb \
  python \
  python-pip \
  python-gdal 

RUN pip install scipy

RUN mkdir /code /data /work
#clone emodis_ndvi_python from https://github.com/gina-alaska/emodis_ndvi_python.git
RUN git clone https://github.com/gina-alaska/emodis_ndvi_python.git /code/emodis_ndvi_python

RUN cd /code/emodis_ndvi_python

ENV HOME_EXC /code/emodis_ndvi_python
ENV HOME_DATA /data

# build info
RUN echo "Timestamp:" `date --utc` | tee /image-build-info.txt
ADD ./hello.sh /hello.sh
#ADD ./2016-test.tar  /2016-test.tar

#
#env USER_ID 1000
#env GROUP_ID 1000
#cmd bash -lc '\
#  build.sh && \
#  chown -R $USER_ID:$GROUP_ID build \
#

RUN chmod u+x /hello.sh
CMD ["./hello.sh"]
